name: vv

on:
  schedule:
    - cron: "0 */6 * * *"   # 每 6 小时执行一次
  workflow_dispatch:        # 手动触发

jobs:
  record:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # GitHub Actions 单次最大运行 6 小时

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 启动 tailscale
      - name: Setup Tailscale
        uses: huggingface/tailscale-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg inotify-tools rclone

      # 配置 rclone
      - name: Setup rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Test rclone config
        run: |
          rclone lsd gdrive:

      # 启动录制脚本
      - name: Run recorder
        env:
          RTSP_URL: ${{ secrets.RTSP_URL }}      
        run: |
          chmod +x ./record.sh
          ./record.sh
