name: record

on:
  workflow_dispatch:        # 手动触发
  schedule:
    # 北京时间 08:30 = UTC 00:30；14:30 = UTC 06:30
    - cron: "30 0 * * 1-5"
    - cron: "30 6 * * 1-5"

permissions:
  contents: read
  actions: write
  id-token: write

concurrency:
  group: record
  cancel-in-progress: false

jobs:
  record:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 最长录制 6 小时

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Tailscale
        uses: huggingface/tailscale-action@main
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg inotify-tools rclone curl

      - name: Setup rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" | base64 --decode > ~/.config/rclone/rclone.conf

      - name: Test rclone config
        run: |
          rclone listremotes || true
          rclone lsd "gdrive:" || echo "⚠️ rclone lsd failed - check remote name"

      - name: Check time window (08:30–20:30 BJT, Mon-Fri)
        id: timecheck
        run: |
          DOW=$(TZ=Asia/Shanghai date +%u)
          NOW=$(TZ=Asia/Shanghai date +%H%M)
          echo "DOW=$DOW, NOW=$NOW"
          if [ "$DOW" -le 5 ] && [ "$NOW" -ge 0830 ] && [ "$NOW" -le 2030 ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Run recorder
        if: steps.timecheck.outputs.run == 'true'
        env:
          RTSP_URL: ${{ secrets.RTSP_URL }}
        run: |
          chmod +x ./record.sh
          ./record.sh

      - name: Skip (outside window)
        if: steps.timecheck.outputs.run != 'true'
        run: echo "Skip:Outside 08:30–20:30 BJT window."

  auto-restart:
    needs: record
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Check window again
        id: gate
        run: |
          DOW=$(TZ=Asia/Shanghai date +%u)
          NOW=$(TZ=Asia/Shanghai date +%H%M)
          if [ "$DOW" -le 5 ] && [ "$NOW" -ge 0830 ] && [ "$NOW" -le 2030 ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger self
        if: steps.gate.outputs.run == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: record.yml
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
